### ISSUE TITLE
错误： Cannot read property 'readdir' of null

### ISSUE THREAD

**Issue by CarryWll** [nxshell/nxshell#107]
sftp通过密码的方式连接失败

**Comment by nxshell** [comment]
@CarryWll  ssh 能链接上吗？

**Comment by CarryWll** [comment]
> @CarryWll ssh 能链接上吗？

可以连接，但是sftp不可以使用

**Comment by CarryWll** [comment]
![image](https://user-images.githubusercontent.com/54405475/139534602-30c5cb6a-0b49-4a35-9022-9186029bd8a9.png)

**Comment by nxshell** [comment]
@CarryWll  sshd 允许了sftp功能吗？ 如果还是不行，联系我们可以具体debug看看什么问题

**Comment by CarryWll** [comment]
> @CarryWll sshd 允许了sftp功能吗？ 如果还是不行，联系我们可以具体debug看看什么问题



> @CarryWll sshd 允许了sftp功能吗？ 如果还是不行，联系我们可以具体debug看看什么问题

![image](https://user-images.githubusercontent.com/54405475/139535509-05d02e30-ed1a-4bf1-9c8c-ffa95561dcd4.png)
如何查看sshd 允许了sftp功能？是这个吗

**Comment by nxshell** [comment]
是啊!看起来允许了啊。。



发自 网易邮箱大师




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2021年10月30日 21:50 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [nxshell/nxshell] 错误： Cannot read property 'readdir' of null (Issue #107) |

@CarryWll sshd 允许了sftp功能吗？ 如果还是不行，联系我们可以具体debug看看什么问题

@CarryWll sshd 允许了sftp功能吗？ 如果还是不行，联系我们可以具体debug看看什么问题


如何查看sshd 允许了sftp功能？是这个吗

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by CarryWll** [comment]
> 是啊!看起来允许了啊。。 发自 网易邮箱大师
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2021年10月30日 21:50 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.******@***.***> | | 主题 | Re: [nxshell/nxshell] 错误： Cannot read property 'readdir' of null (Issue #107) | @CarryWll sshd 允许了sftp功能吗？ 如果还是不行，联系我们可以具体debug看看什么问题 @CarryWll sshd 允许了sftp功能吗？ 如果还是不行，联系我们可以具体debug看看什么问题 如何查看sshd 允许了sftp功能？是这个吗 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

应该是服务器的问题，我连接其他服务器都可以，只有那一台不可以，那一台只可以使用SecureFX_x64打开

> 是啊!看起来允许了啊。。 发自 网易邮箱大师
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2021年10月30日 21:50 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.******@***.***> | | 主题 | Re: [nxshell/nxshell] 错误： Cannot read property 'readdir' of null (Issue #107) | @CarryWll sshd 允许了sftp功能吗？ 如果还是不行，联系我们可以具体debug看看什么问题 @CarryWll sshd 允许了sftp功能吗？ 如果还是不行，联系我们可以具体debug看看什么问题 如何查看sshd 允许了sftp功能？是这个吗 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

应该是服务器的问题，我连接其他服务器都可以，只有那一台不可以，那一台只可以使用SecureFX_x64打开

> 是啊!看起来允许了啊。。 发自 网易邮箱大师
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2021年10月30日 21:50 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.******@***.***> | | 主题 | Re: [nxshell/nxshell] 错误： Cannot read property 'readdir' of null (Issue #107) | @CarryWll sshd 允许了sftp功能吗？ 如果还是不行，联系我们可以具体debug看看什么问题 @CarryWll sshd 允许了sftp功能吗？ 如果还是不行，联系我们可以具体debug看看什么问题 如何查看sshd 允许了sftp功能？是这个吗 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

应该是服务器的问题，我连接其他服务器都可以，只有那一台不可以，那一台只可以使用SecureFX_x64打开

**Comment by nxshell** [comment]
@CarryWll  进qq群可以看哈具体什么问题
