### ISSUE TITLE
双击打开。sftp默认打开当前路径、sftp可拖放下载

### ISSUE THREAD

**Issue by qq8554650** [nxshell/nxshell#11]
1、双击左侧主机、双击已打开主机的标签，应打开一个终端。原因很多
2、点击右上角sftp时，应打开当前路径。因为这时候很可能需要下载当前目录文件
3、可以拖放到本地文件夹
4、证书目前不支持密码

other：安装包好大好大^^

**Comment by nxshell** [comment]
2、4将在下次小版本更新

**Comment by nxshell** [comment]
1，2，4已经更新 v1.1.1

**Comment by nxshell** [comment]
v1.2.0
