### ISSUE TITLE
能否增加多窗口模式

### ISSUE THREAD

**Issue by hetian127** [nxshell/nxshell#117]
希望可以多窗口同屏展示，谢谢

**Comment by nxshell** [comment]
Fixed in v1.6.5

**Comment by hetian127** [comment]
请问具体如何使用“多窗口同屏展示”呢？没有找到方法，感谢

**Comment by nxshell** [comment]
Right click on session.
![图片](https://user-images.githubusercontent.com/74552956/189298404-8cc06f51-f99f-4272-8352-77c9c35a65a7.png)
