### ISSUE TITLE
界面与新建ssh设置可以借鉴下electerm的 比较简洁美观

### ISSUE THREAD

**Issue by hummingsoul** [nxshell/nxshell#123]

**Comment by etanman** [comment]
你别说，nxshell还真的与electerm比较像，连对话框无法自动焦点问题都一样。不过好在nxshell支持telnet

**Comment by hummingsoul** [comment]
> 你别说，nxshell还真的与electerm比较像，连对话框无法自动焦点问题都一样。不过好在nxshell支持telnet

眼瘸?  哪比较像?   都是ssh工具??
