### ISSUE TITLE
设置Unicode（UTF-8）编码后，Linux系统中中文显示正常，部分其它编码配置文件中文显示异常

### ISSUE THREAD

**Issue by Long-Tu** [nxshell/nxshell#132]
# 设置Unicode（UTF-8）编码后，Linux系统中中文显示正常，部分其它编码配置文件中文显示异常
## 使用Unicode编码的配置文件， 中文显示正常
![图片](https://user-images.githubusercontent.com/37840939/144965682-36397846-9595-49f0-9cd3-78fdab87cd29.png)

正常显示配置文件
## 使用其它编码的配置文件， 中文显示异常
![图片](https://user-images.githubusercontent.com/37840939/144965731-6bafc8b2-fbe5-4a5c-b289-6f9859478af3.png)

建议：Linux系统中的编码和配置文件中的编码做分离，配置文件中编码可以自动识别或者可以手动选择，不然就会出现Linux系统与配置文件没法兼容，总会出现一个是乱码的情况

**Comment by nxshell** [comment]
这个超过了作为ssh终端的配置，ssh终端应该是保证ssh session编解码的配置。
