### ISSUE TITLE
"确认关闭该会话"?这个提示过于繁琐了,觉得可以简化一下.

### ISSUE THREAD

**Issue by ywp-repo** [nxshell/nxshell#138]

**Comment by nxshell** [comment]
去掉吗？

**Comment by ywp-repo** [comment]
不是去除,,,比如有些,"关闭"操作就没有必要在给这个提示了.现在的操作应该是只要是点击"标签页"的"关闭"就会提示这个"确认关闭该会话"这个对话框.个人觉得没这个必要去时时提醒的,,旨在关键窗口防止误操作给个提示即可,比如,打开了一个服务器连接窗口标签页,当关闭这个服务器标签时,这种带有危险性的操作时.,,,,其他的类似"设置""修改"会话属性等等这些非关键重要性的操作个人觉得没必要提示是否要关闭这样的提示的.

**Comment by nxshell** [comment]
thanks! 我们可以考虑下



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年01月13日 23:34 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [nxshell/nxshell] "确认关闭该会话"?这个提示过于繁琐了,觉得可以简化一下. (Issue #138) |

不是去除,,,比如有些,"关闭"操作就没有必要在给这个提示了.现在的操作应该是只要是点击"标签页"的"关闭"就会提示这个"确认关闭该会话"这个对话框.个人觉得没这个必要去时时提醒的,,旨在关键窗口防止误操作给个提示即可,比如,打开了一个服务器连接窗口标签页,当关闭这个服务器标签时,这种带有危险性的操作时.,,,,其他的类似"设置""修改"会话属性等等这些非关键重要性的操作个人觉得没必要提示是否要关闭这样的提示的.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by hongruiji** [comment]
确实有点频繁了，建议要么直接去掉，要么加个设置项，不再提示。

**Comment by zeakey** [comment]
Agree. For tabs that are already disconnected from the remote server can be safely closed without alter.

**Comment by bzw1204** [comment]
最新版本已更新优化，请更新到最新版本体验，感谢关注与建议！
