### ISSUE TITLE
密码方式登录报错，交互式密码登录就可以

### ISSUE THREAD

**Issue by liy516** [nxshell/nxshell#139]
如题！

**Comment by nxshell** [comment]
重新输入密码试一下。可能输入错误了



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年01月12日 21:33 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [nxshell/nxshell] 密码方式登录报错，交互式密码登录就可以 (Issue #139) |

如题！

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
