### ISSUE TITLE
增加功能: SSH连接上后的选项卡可以随便移动,变换位置

### ISSUE THREAD

**Issue by leslieDD** [nxshell/nxshell#141]
SSH连接上后的选项卡可以随便移动,变换位置.
有时候,多个SSH连接上了,想把同一台机器的放在一起.

**Comment by dysf888** [comment]
+1 另外希望连接成功之后 欢迎标签 自动关闭

**Comment by bzw1204** [comment]
最新版本已支持,请下载体验！感谢支持与建议！
