### ISSUE TITLE
Error: All configured authentication methods failed ；Network is disconnected

### ISSUE THREAD

**Issue by jj392502304** [nxshell/nxshell#143]
![image](https://user-images.githubusercontent.com/41356863/154633532-74ed0546-eebc-4c3f-84fc-30ff5a61566d.png)

**Comment by nxshell** [comment]
配置文件里要配置登录密码



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年02月18日 15:00 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [nxshell/nxshell] Error: All configured authentication methods failed ；Network is disconnected (Issue #143) |

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
