### ISSUE TITLE
mac 登陆linux home目录无法打开

### ISSUE THREAD

**Issue by leevisliu** [nxshell/nxshell#150]
mac 登陆linux home目录无法打开

**Comment by nxshell** [comment]
您好，请问是Mac客户端ssh Linux机器无法打开home？ 能具体描述下吗？Mac版本 Linux发行版本等信息。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年04月18日 22:43 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [nxshell/nxshell] mac 登陆linux home目录无法打开 (Issue #150) |

mac 登陆linux home目录无法打开

**Comment by leevisliu** [comment]
![image](https://user-images.githubusercontent.com/31270182/163829453-582a544a-781e-4060-80e1-6ca7d944e760.png)

**Comment by leevisliu** [comment]
版本是12.2.1

**Comment by leevisliu** [comment]
Mac ver:12.2.1
Linux CentOS Linux release 7.9.2009 (Core)

**Comment by nxshell** [comment]
看截图不是在home目录下嘛？是有些文件没有显示吗？ 可以ssh登录 ls看下是什么文件无法显示吗？



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年04月18日 23:15 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [nxshell/nxshell] mac 登陆linux home目录无法打开 (Issue #150) |

Mac ver:12.2.1
Linux CentOS Linux release 7.9.2009 (Core)

**Comment by nxshell** [comment]
在home目录用mkdir命令新建个test文件夹看看 能打开吗？
还有不能打开的文件夹是ls -al看看。


看截图不是在home目录下嘛？是有些文件没有显示吗？ 可以ssh登录 ls看下是什么文件无法显示吗？




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年04月18日 23:15 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [nxshell/nxshell] mac 登陆linux home目录无法打开 (Issue #150) |

Mac ver:12.2.1
Linux CentOS Linux release 7.9.2009 (Core)

**Comment by leevisliu** [comment]
![image](https://user-images.githubusercontent.com/31270182/163944696-8b742d66-7d52-401b-94ea-f607c4865422.png)
我今天在windows上安装nxshell 跑了一下 和mac机器上一样的 ，具体问题是这样的：在/home/目录下有个neween 目录，用sftp打开远程目录 显示neween是灰色的，双击无法点开，但是这个目录下面其实是有子目录和文件的。
不知道我现在描述清楚没？如有我没描述清楚的地方 我发一下邮件 我把root密码给你测试一下

**Comment by leevisliu** [comment]
> 在home目录用mkdir命令新建个test文件夹看看 能打开吗？ 还有不能打开的文件夹是ls -al看看。 看截图不是在home目录下嘛？是有些文件没有显示吗？ 可以ssh登录 ls看下是什么文件无法显示吗？
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2022年04月18日 23:15 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.******@***.***> | | 主题 | Re: [nxshell/nxshell] mac 登陆linux home目录无法打开 (Issue #150) | Mac ver:12.2.1 Linux CentOS Linux release 7.9.2009 (Core) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

**Comment by leevisliu** [comment]
是在root目录下

**Comment by leevisliu** [comment]
抱歉 是我自己的问题  路径搞错了  谢谢解答
