### ISSUE TITLE
希望增加双击克隆终端类似xshell，很常用

### ISSUE THREAD

**Issue by damondengxin** [nxshell/nxshell#154]
希望增加双击克隆终端类似xshell，很常用。谢谢！代码后续会开源吗？如果有机会希望也能帮忙做点贡献！

**Comment by nxshell** [comment]
现在在tab中右键可以复制链接，在下面的+号也能复制会话



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年05月04日 21:58 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [nxshell/nxshell] 希望增加双击克隆终端类似xshell，很常用 (Issue #154) |

希望增加双击克隆终端类似xshell，很常用。谢谢！代码后续会开源吗？如果有机会希望也能帮忙做点贡献！

**Comment by bzw1204** [comment]
> 双击克隆终端类似xshell
代码已开源，欢迎pr，感谢支持！
[https://github.com/nxshell/shell](https://github.com/nxshell/shell)
