### ISSUE TITLE
I suggest adding the function of batch file operation

### ISSUE THREAD

**Issue by cangkui** [nxshell/nxshell#161]
When I used the SFTP File Transfer funtion of NxShell, I found that although I can select more than one file, I can only operate one of them. It makes trouble when I want to delete a batch of files in one operation. I've experienced this function in Xftp and i get used to it. It will be pretty nice if you can add the function of batch file operation in future version.

**Comment by nxshell** [comment]
Got it!  thanks! @cangkui

**Comment by nxshell** [comment]
Fixed  v1.6.0
