### ISSUE TITLE
1.5.4全局设置字体大小异常

### ISSUE THREAD

**Issue by waitsaber** [nxshell/nxshell#175]
在1.5.4中如果先创建好了会话再修改全局设置中的字体大小后，已经创建好的会话即使重连也不会被修改字体大小，只有先设置好全局设置中的字体大小再新建会话，这样会话才会套用全局的字体大小设置。

**Comment by nxshell** [comment]
![图片](https://user-images.githubusercontent.com/74552956/171536522-fdcdfdf6-a275-4122-a14b-8cba048e36a9.png)
session配置里面字体大小选择default， 才能去引用全局配置字体大小 @waitsaber

**Comment by waitsaber** [comment]
如果是这样的话，我还是建议在新建会话的时候字体大小就是default选项，现在新建会话是直接读取全局设置的字体大小的，也就是说全局设置字体大小是18px，新建的会话字体大小也是18px，我的建议是新建的时候不要自动去选择跟全局一样的字体大小，应该是默认default 这样后面如果更改了全局设置才不用一个个会话去修改。
