### ISSUE TITLE
macbookpro m1 无法输入中文

### ISSUE THREAD

**Issue by zhangyf35** [nxshell/nxshell#179]
不论是系统自带中文输入法，还是搜狗都输不了中文

**Comment by zhangyf35** [comment]
版本 1.6.0

**Comment by nxshell** [comment]
mac我们是在i5上面打包的啊， m1也能运行？ @zhangyf35

**Comment by zhangyf35** [comment]
> mac我们是在i5上面打包的啊， m1也能运行？ @zhangyf35

可以运行，转译运行的， 我重启了几次又可以输入中文了
