### ISSUE TITLE
设置页面标签部分不跳转

### ISSUE THREAD

**Issue by milkbrother666** [nxshell/nxshell#181]
录了一个比较短的视频来说明 [点击](https://streamja.com/ar9kJ)

具体描述就是在设置页面点击<登录认证>的标签不会自动跳转到对应的部分

**Comment by bzw1204** [comment]
![image](https://user-images.githubusercontent.com/9693637/209640743-adb71c40-f8ac-41a3-8ca6-b4f40da62560.png)
请提供下你的软件版本，若不是最新的，请更新到最新版体验，感谢支持！
