### ISSUE TITLE
多标签页使用时，关闭标签页可能导致同一台服务器连接丢失，以及新创意

### ISSUE THREAD

**Issue by milkbrother666** [nxshell/nxshell#182]
录了一个简短的视频说明情况：[点我](https://streamja.com/P5o3M)

新功能开发：希望能够拖动标签页

**Comment by milkbrother666** [comment]
简单描述：
A标签页连接上A服务器，此时复制A标签页得到B标签页，然后关闭A标签页会导致B标签页连接丢失；而关闭B标签页并不会导致A标签页丢失。
如果在B标签页上再复制一个C标签页，关闭B标签页会导致C标签页连接丢失，而不影响A标签页
如果在A标签页上复制两个新的标签页为A1和A2，A2为比A1晚复制出来。此时关闭A2将不会影响到其它标签页的使用；但是关闭A1会导致A2连接丢失，A标签页正常使用

**Comment by bzw1204** [comment]
最新版本已修复！请更新到最新版本体验，感谢支持与建议！
