### ISSUE TITLE
为啥没有源码

### ISSUE THREAD

**Issue by zhuhedong** [nxshell/nxshell#183]

**Comment by nxshell** [comment]
暂未开源

**Comment by jrt324** [comment]
那在readme里面也不要声称说是open source的啊，会让人抓话柄的

**Comment by nxshell** [comment]
请你仔细看readme 里面的源码地址



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年08月25日 18:43 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>、State ***@***.***> |
| 主题 | Re: [nxshell/nxshell] 为啥没有源码 (Issue #183) |

那在readme里面也不要声称说是open source的啊，会让人抓话柄的
