### ISSUE TITLE
Control + Click does not open the link

### ISSUE THREAD

**Issue by Hiram-Wong** [nxshell/nxshell#195]
# Problem Description: Control + Click not open the link

> NXShell version:1.6.0 
> macOS version:Ventura 13.0 Beta (22A5286j)

![image.png](https://s2.loli.net/2022/07/04/iyZeABzm5DJQcsw.png)

**Comment by zeakey** [comment]
Seems like a bug, I came into the same problem by myself. We will focus on this and try to fix it in the next release.

Thanks.

**Comment by bzw1204** [comment]
> # Problem Description: Control + Click not open the link
> > NXShell version:1.6.0
> > macOS version:Ventura 13.0 Beta (22A5286j)
> 
> ![image.png](https://camo.githubusercontent.com/f9c6282983a6c71b3ac7e2aee770c95f9f65309e0a86fa4fb34e1fb1fc26c4ee/68747470733a2f2f73322e6c6f6c692e6e65742f323032322f30372f30342f69795a6541427a6d35444a516373772e706e67)

Please update to the latest version to use, thanks for your feedback.
