### ISSUE TITLE
希望添加快捷命令模块。

### ISSUE THREAD

**Issue by DharmaBums1991** [nxshell/nxshell#203]
希望大佬能增加预存快捷命令功能，祝大佬工作顺利！

**Comment by zeakey** [comment]
Please read our [Guidance for new issues](https://github.com/nxshell/nxshell/issues/192) before creating new issues.

1. please create new issues **in English**;
2. feature requests should be posted in [Feature requests](https://github.com/nxshell/nxshell/issues/193)
