### ISSUE TITLE
brew command not found in Mac

### ISSUE THREAD

**Issue by tocky0** [nxshell/nxshell#204]
Macos, 10.15.7  
I installed many commands through brew, but these all cmd not found in Nxshell.    
When use Item, these cmd can be found.  
Executing `source ~/.bash_profile `  in Nxshell, has exception `bash: brew: command not found`.  
So, how to fix to make these cmd work?

**Comment by nxshell** [comment]
It's like a process ENV not effect in electron

**Comment by nxshell** [comment]
@tocky0   echo your ENV  path in NxShell, then check if `brew` command in the paths.

**Comment by tocky0** [comment]
yes. `env` not include the path `/usr/local/bin/brew`, when update `source ~/.bash_profile` and exec , it work.   
Thansk for this.  
As i know, macOs terminal default use zsh, but the `~/.zshrc` already has the code `source ~/.bash_profile`, but Nxshell maybe not source it?  when use macOs default terminal, no this problem.

**Comment by nxshell** [comment]
yes，nxshell use bash as default terminal。 we would fix in next release。



---- Replied Message ----
| From | ***@***.***> |
| Date | 07/20/2022 10:44 |
| To | ***@***.***> |
| Cc | ***@***.******@***.***> |
| Subject | Re: [nxshell/nxshell] brew command not found in Mac (Issue #204) |

yes. env not include the path /usr/local/bin/brew, when update source ~/.bash_profile and exec , it work.
Thansk for this.
As i know, macOs terminal default use zsh, but the ~/.zshrc already has the code source ~/.bash_profile, but Nxshell maybe not source it? when use macOs default terminal, no this problem.

**Comment by nxshell** [comment]
fixed v1.6.2

**Comment by tocky0** [comment]
> 



> fixed v1.6.2

By the way, since version 1.6.1, is the DMG install package for macOS no longer available?  
I didn't find or see any instructions

**Comment by nxshell** [comment]
MacOS package at http://106.15.238.81:52080/



---- Replied Message ----
| From | ***@***.***> |
| Date | 08/01/2022 10:05 |
| To | ***@***.***> |
| Cc | ***@***.***>、State ***@***.***> |
| Subject | Re: [nxshell/nxshell] brew command not found in Mac (Issue #204) |

fixed v1.6.2

By the way, since version 1.6.1, is the DMG install package for macOS no longer available?
I didn't find or see any instructions
