### ISSUE TITLE
功能建议： 能否在后续版本中增加命令编辑窗口，xshell和crt 中都比较常用到

### ISSUE THREAD

**Issue by yrjjf** [nxshell/nxshell#205]
缺少了命令编辑窗口，这个功能在xshell和crt中经常用到。是否考虑在后续版本中增加。
命令发送前可以很便捷的修改命令

**Comment by zeakey** [comment]
Please please read our [guidance to new issues](https://github.com/nxshell/nxshell/issues/192) before creating a new issue.

For feature request, please comment under [Feature requests](https://github.com/nxshell/nxshell/issues/193) instead of raising a new issue.

Thanks.
