### ISSUE TITLE
ssh登录错误

### ISSUE THREAD

**Issue by llucky2022** [nxshell/nxshell#207]
登录虚拟机时显示
Hello NxShell !

Network is disconnected
Error: Unable to request a pseudo-terminal

虚拟机Rocky Linux 9 最小安装，用putty可以正常ssh登录
 - OS: windows 11 VirtuBox 
 - NxShell Version [ 1.6.2]

**Comment by zeakey** [comment]
Please read our [guidance to new issues](https://github.com/nxshell/nxshell/issues/192) before creating a new issue. 

* To bring NxShell to worldwide users and build an international community, we encourage you to rise new issues in English. We understand this may be awkward for many of our users, but using a language that is understandable by worldwide users is the key to the spread and impact of NxShell.
