### ISSUE TITLE
如何设置代理服务器

### ISSUE THREAD

**Issue by ChristmasZCY** [nxshell/nxshell#209]
请问如何通过跳板机登录呢

**Comment by zeakey** [comment]
Please read our [guidance to new issues](https://github.com/nxshell/nxshell/issues/192) before creating a new issue. 

* To bring NxShell to worldwide users and build an international community, we encourage you to rise new issues in English. We understand this may be awkward for many of our users, but using a language that is understandable by worldwide users is the key to the spread and impact of NxShell.

**Comment by ChristmasZCY** [comment]
I want log in my server through other server, how can I do it
