### ISSUE TITLE
建议: 希望能增加类似xshell 或者secureCRT那种, 日志录制功能.

### ISSUE THREAD

**Issue by chengyiqun** [nxshell/nxshell#21]
xshell 和 secureCRT 有个很方便的功能. 
以xshell为例: 
打开 文件 日志 启动
会建立一个文本文件, 然后就可以把之后终端上刷屏的文本记录到文本文件了.
方便测试人员抓取日志使用. 
tail -f 到文件, 再sz还是麻烦了点.

**Comment by nxshell** [comment]
Release v1.4.0， 在终端开启后右键点击管理日志

**Comment by an2e9ingC** [comment]
日志的路径可否支持自定义路径和文件名命名自定义呢？ @nxshell
