### ISSUE TITLE
Error: getaddrinfo ENOTFOUND myip

### ISSUE THREAD

**Issue by tocky0** [nxshell/nxshell#210]
nxshell 1.6.2  
windows 10  
when add a connection，and double click connection name to connect, exception as flow,  
`Error: getaddrinfo ENOTFOUND  97.64.x.x`  
so this is a bug?

**Comment by nxshell** [comment]
It seem to a space  in your input ip.

**Comment by nxshell** [comment]
workaround for this version:  reinput you ip again without space at head or tail.

**Comment by tocky0** [comment]
oh,my fault. ip string has space.  
but,maybe if the ip string be trim space character by nxshell auto, it will be better.  
like spaces, tabs, newlines, and carriage returns.
Thanks.

**Comment by nxshell** [comment]
yes，will fix next release!
