### ISSUE TITLE
Cannot drag to move tabs

### ISSUE THREAD

**Issue by oison111** [nxshell/nxshell#211]
这里不能拖动位置啊   是我的电脑问题吗

![image](https://user-images.githubusercontent.com/102855127/182185301-ee292946-3330-4cec-a2c9-9afd00d7aeb0.png)

**Comment by oison111** [comment]
![image](https://user-images.githubusercontent.com/102855127/182185499-1ad1b758-58e2-44ed-8472-400df05a0d09.png)

**Comment by nxshell** [comment]
not support drag the tabs

**Comment by bzw1204** [comment]
请更新到最新版本V1.9.2体验，感谢你的关注与支持！
