### ISSUE TITLE
app ui blurred,maybe electron or develop environment 

### ISSUE THREAD

**Issue by tocky0** [nxshell/nxshell#215]
macos 10.15.7  
nxshell 1.6.2  
My develop mac have install many dev software,such as vscode, nxshell, youdao note，firefox, etc. maybe they all use electron tech. now some of these UI are blurred almost simultaneously, like screenshot,
<img width="719" alt="0886b806-3a46-43d6-9b65-310efb0c8a78" src="https://user-images.githubusercontent.com/5350993/184789308-1cfac6b7-5fb5-45b6-bbb7-9a2a54f797a9.png">  

<img width="1036" alt="c9c1c73b-1ef1-43b9-8846-64f4b6fa340a" src="https://user-images.githubusercontent.com/5350993/184789334-c216f37a-ff3a-49f5-9cf6-15e2ffeec22a.png">  
  
  
so this is the electron compatible conflict or some others?    
or can restart electron, not restart pc. because restart nxshell ui blurred is still exist.
Thanks!

**Comment by nxshell** [comment]
it still blue when restart macos pc? @tocky0

**Comment by tocky0** [comment]
> it still blue when restart macos pc? @tocky0

when restart macos pc, nxshell and other electron software are all recover.
But, what the reason?

**Comment by nxshell** [comment]
Maybe electron issue...
