### ISSUE TITLE
Can't select all output characters at once

### ISSUE THREAD

**Issue by an2e9ingC** [nxshell/nxshell#217]
**Describe the bug**
Can't select all output characters at once, users must select all characters using mouse line by line.
无发一键快速选中所有输出的字符，必须要通过鼠标一行一行的操作，尤其是当输出信息比较多时，不是很方便呢。

**To Reproduce**
NULL

**Expected behavior**
Users could select all output characters using A hot key, like CTRL+A.

**Screenshots**
NULL.

**Desktop (please complete the following information):**
 - OS: [Windows]
 - OS Version [Win10]
 - NxShell Version [1.6.3]

**Additional context**
Aoligei...
加油，奥里给！

**Comment by nxshell** [comment]
Will implement in next release

**Comment by nxshell** [comment]
fixed in v1.6.4
