### ISSUE TITLE
tab display complete not fix at 1.6.4

### ISSUE THREAD

**Issue by xingsu1021** [nxshell/nxshell#218]
fixed in v1.6.4

_Originally posted by @nxshell in https://github.com/nxshell/nxshell/issues/216#issuecomment-1229192263_

if use ip_aliasname,it display ip_...，please check it。
如果使用ip_其它名称命名的，ip完整，但是别名还是省略号。不能像crt和MobaXterm那样显示完整

![](https://z4a.net/images/2022/08/30/QQ20220830190824.png)

**Comment by xingsu1021** [comment]
Can you open it up so it's clear。
不知道是否可以放开，自适应模式

**Comment by nxshell** [comment]
won't fix
