### ISSUE TITLE
win11 language setting does not work

### ISSUE THREAD

**Issue by xingsu1021** [nxshell/nxshell#219]
set language Chinese and save. close windows and open new, I found the languages is English.

![](https://z4a.net/images/2022/08/30/ch.png)
![](https://z4a.net/images/2022/08/30/en.png)

**Comment by nxshell** [comment]
need to restart APP



---- Replied Message ----
| From | ***@***.***> |
| Date | 08/30/2022 19:29 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | [nxshell/nxshell] win11 language setting does not work (Issue #219) |

set language Chinese and save. close windows and open new, I found the languages is English.

**Comment by nxshell** [comment]
which version？



---- Replied Message ----
| From | ***@***.***> |
| Date | 08/30/2022 19:40 |
| To | ***@***.***> |
| Cc | ***@***.******@***.***> |
| Subject | Re: [nxshell/nxshell] win11 language setting does not work (Issue #219) |

I do it.but invalid

**Comment by xingsu1021** [comment]
I found my home win11 is ok.office do not work. sorry,please ignore  this.
