### ISSUE TITLE
有点操作逻辑上的小问题.

### ISSUE THREAD

**Issue by bigcaibao** [nxshell/nxshell#23]
我习惯性的点右上角的X来让软件最小化到Windows托盘哪里.

现在的操作逻辑是点X,软件直接关闭,并没有提示说会退出软件.这个我想应该给个选项吧,点X是关闭,还是隐藏到托盘.

另外能否添加一个自定义终端配色的功能,开发者辛苦.

**Comment by bigcaibao** [comment]
其他的问题目前还没发现,才试用了一下,我倒是不怎么在意数据同步,单机版是最好的.
再就是有人提出的RDP,为啥不增加一个调用系统mstsc,挺好.我想很多人跟我一样应该手里不止是只有Linux终端吧.

**Comment by nxshell** [comment]
@bigcaibao 终端配色开发中。 其他问题会在后期考虑优化！

**Comment by bigcaibao** [comment]
@nxshell 使用github登录,然后把数据加密上传到github.哈哈.这样同步.还省了同步服务器.每个人单独一个密钥.

**Comment by nxshell** [comment]
> 
> 
> @nxshell 使用github登录,然后把数据加密上传到github.哈哈.这样同步.还省了同步服务器.每个人单独一个密钥.

同步配置文件，主要设计的应用场景是企业管理服务器登录，只给授权的用户配置需要的服务器登录用户名密码或者秘钥。这样企业管理员就负责管理服务器资产，员工只负责同步配置 直接登录就行了，不要知道ip，密码，秘钥这些数据。

**Comment by bigcaibao** [comment]
@nxshell 哪如果个人用户有同步需求呢,比如我在办公地点的数据想同步到家里的电脑上来.

**Comment by nxshell** [comment]
@bigcaibao 暂时你可以通过导入导出实现。。。

**Comment by bigcaibao** [comment]
@nxshell 欸,这个功能好,我觉得比同步要实在,而且数据安全自己可以保障.导入导出,nice,
