### ISSUE TITLE
串口波特率无法设置为1500000

### ISSUE THREAD

**Issue by Near2U0** [nxshell/nxshell#233]
**Describe the bug**
串口波特率无法设置为1500000

**To Reproduce**
在会话属性中设置串口波特率 最大是115200，而我需要设置为1500000。
在MobaXterm中是可以手动输入指定波特率的

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - OS Version [e.g. 22]
 - NxShell Version [e.g. 1.6.2]

**Additional context**

**Comment by bzw1204** [comment]
> **Describe the bug** 串口波特率无法设置为1500000
> 
> **To Reproduce** Steps to reproduce the behavior: 在会话属性中设置串口波特率 最大是115200，而我需要设置为1500000。 在MobaXterm中是可以手动输入指定波特率的
> 
> **Expected behavior** A clear and concise description of what you expected to happen.
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **Desktop (please complete the following information):**
> 
> * OS: [e.g. Windows]
> * OS Version [e.g. 22]
> * NxShell Version [e.g. 1.6.2]
> 
> **Additional context** Add any other context about the problem here.

最新版本1.9.4以支持手动输入，请更新使用
