### ISSUE TITLE
Error: Unable to request a pseudo-terminal

### ISSUE THREAD

**Issue by leslieDD** [nxshell/nxshell#234]
**Describe the bug**
配置好名称，IP地址，使用密码登录，配置好账号和密码，保存，连接，出现以下问题：
```
Hello NxShell !
Error: Unable to request a pseudo-terminal
```
截图：
![image](https://user-images.githubusercontent.com/5474698/197491984-b62328f3-ce10-487a-8d85-72e76ad48af7.png)

NxShell的安装程序：`NxShell-x64-win-1.8.0-202209141343.exe`
NxShell运行的操作系统：`Windows 10 专业版 21H2 `
被连接的系统是：`CentOS Stream release 9`
被连接的SSH版本： `OpenSSH_8.7p1, OpenSSL 3.0.1 14 Dec 2021`
被连接的系统安装在平台：`Hyper-V`
被连接的系统可以被其它工具正常连接：`xshell` 和 `ssh命令`

**Comment by bzw1204** [comment]
请更新到最新版！

**Comment by XuruiPro** [comment]
我也是这个情况

**Comment by XuruiPro** [comment]
NxShell的安装程序：NxShell-x86_64-linux-1.9.0-202211250327.AppImage
NxShell运行的操作系统：Deepin 20.8 11038.007
被连接的系统是：Rocky Linux 9.0
被连接的SSH版本：OpenSSL 3.0.1 14 Dec 2021
被连接的系统安装在平台：实体主机
被连接的系统可以被其它工具正常连接：xshell 和 ssh命令

**Comment by saber-project** [comment]
Unfortunately, this problem has not been completely solved, and some cloud service providers' VPS cannot connect normally, but the above error is still returned. (The system can connect normally in normal shell windows)
Is it possible to provide a function in the settings that allows the user to customize the setting "Do you force pseudo-terminal connections to be accepted"?Unfortunately, this problem has not been completely solved, and some cloud service providers' VPS cannot connect normally, but the above error is still returned. (The system can connect normally in normal shell windows)
Is it possible to provide a function in the settings that allows the user to customize the setting "Do you force pseudo-terminal connections to be accepted"?

**Comment by leslieDD** [comment]
```
Hello NxShell !
Error: Unable to request a pseudo-terminal
```
一样的问题
nxshell版本: 1.9.3 
操作系统版本: Ubuntu 22.04.2 LTS \n \l
被远程连接的系统版本: CentOS Stream release 9

其它工具正常，如xshell , ssh

**Comment by leslieDD** [comment]
这个问题用以下方式可以解决：
```bash
$ sudo update-crypto-policies --set DEFAULT:SHA1
$ sudo reboot
```
参考：
https://community.thinlinc.com/t/mac-osx-12-4-client-issue/413/6
