### ISSUE TITLE
会话实例关闭按钮可否添加是否提醒设置

### ISSUE THREAD

**Issue by soulferrydcd** [nxshell/nxshell#239]
![image](https://user-images.githubusercontent.com/44570499/203212207-91c33a8e-86a5-4856-bbde-a1c350e2079c.png)
有时候需要关闭多个会话，每一个都提示是不是不太友好，可否劳烦作者加一个开关，即可关闭该提醒弹窗，谢谢

**Comment by bzw1204** [comment]
最新版本以支持相关操作，请更新致V1.9.2版本使用
