### ISSUE TITLE
sftp快速编辑无法关闭页签

### ISSUE THREAD

**Issue by LoseAccount233** [nxshell/nxshell#241]
**Describe the bug**
sftp的快捷编辑功能无法在不保存修改的情况下关闭tab

**To Reproduce**
1. 服务器服务器
2. 打开stp并快速打开一个文件编辑
3. 点关闭按钮
4. 无论点差还是取消都无法结束文件快速编辑操作,如果想关闭就必须要保存

![image](https://user-images.githubusercontent.com/119295896/204248222-a72c664f-8cac-489a-8c48-699511e6f525.png)

**Comment by nxshell** [comment]
sftp close note need different ssh session
