### ISSUE TITLE
The selected text of the default theme in sftp cannot be highlighted

### ISSUE THREAD

**Issue by waittingsummer** [nxshell/nxshell#249]
**The selected text of the default theme in sftp cannot be highlighted**

**Screenshots**
![8O1{}VKAZMJBLKI8 HZ9PFH](https://user-images.githubusercontent.com/32017265/208032741-6cf32f66-04b9-46a6-812b-b590c81e5a8c.png)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - OS Version [22H2]
 - NxShell Version [1.91]

**Comment by bzw1204** [comment]
![image](https://user-images.githubusercontent.com/9693637/209630016-81703253-829f-4887-a6b6-fe455dcd211c.png)
The file is quite large. Please wait patiently. It can be highlighted normally

**Comment by bzw1204** [comment]
The new version is fix, please update V1.9.2 to use,Thanks for you support!

**Comment by waittingsummer** [comment]
Unfortunately, in my testing, version 1.92 does not fix this problem。

**Comment by bzw1204** [comment]
> Unfortunately, in my testing, version 1.92 does not fix this problem。

Please take a look later, the code has just been submitted and merged, and there will be a new version later, please pay attention

**Comment by bzw1204** [comment]
> Unfortunately, in my testing, version 1.92 does not fix this problem。

Hi,Please re-download V1.9.2 version installation
