### ISSUE TITLE
字体自定义支持

### ISSUE THREAD

**Issue by jxcangel** [nxshell/nxshell#25]
目前字体只能选择大小，但是不能自定义字体，我的终端使用了 powerline 并启用了 Fira Code 字体，现在默认字体很多特殊字符显示不出来

![image](https://user-images.githubusercontent.com/3955609/124700081-a8dcfd00-df1e-11eb-8611-369e6986ffc1.png)

希望可以自定义字体类型

**Comment by nxshell** [comment]
@jxcangel  支持的字体选择配置，能测试反馈下吗
