### ISSUE TITLE
Syntax highlighting of the second half of the sftp configuration file fails

### ISSUE THREAD

**Issue by waittingsummer** [nxshell/nxshell#251]
**Syntax highlighting of the second half of the sftp configuration file fails**

**Screenshots**
![YU{A69`( 2SLE0NBV0B6@Z8](https://user-images.githubusercontent.com/32017265/208035236-23dfc464-7daa-4e93-b267-065f43effb0a.png)

![L31` 08{V9{59{5~4SSUE0O](https://user-images.githubusercontent.com/32017265/208035253-3335511a-bf09-445c-8855-c5e16cd7a9ac.jpg)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - OS Version [22H2]
 - NxShell Version [1.91]

**Comment by bzw1204** [comment]
> 
Can you provide your documents

**Comment by waittingsummer** [comment]
> > 
> 
> Can you provide your documents

[cassandra.zip](https://github.com/nxshell/nxshell/files/10306441/cassandra.zip)

**Comment by bzw1204** [comment]
The file is quite large. Please wait patiently. It can be highlighted normally
![image](https://user-images.githubusercontent.com/9693637/209630667-fc67dda5-125c-438f-9d74-0e50a0bada35.png)
