### ISSUE TITLE
多次新建会话会导致卡住无法新建

### ISSUE THREAD

**Issue by elmagnificogi** [nxshell/nxshell#255]
版本：1.9.2 当前最新release
系统：win10

使用UI上的+号多次新建会话会导致卡住无法新建

每次新建的会话都是真实有效的，多建几次就会发现，再点加号，左侧会话栏没有出现新的未命名主机，但是新建会话的界面显示了，然后填好设置以后，是无法保存，无法连接的

Feature：
导出的时候能不能选择性导出，而不是默认所有会话都导出了

还有一点，所有UI交互都有一点卡卡的感觉，对比xshell等其他shell，绝对没有这种迟滞的感觉

**Comment by bzw1204** [comment]
非常感谢你的反馈，我们会尽力优化！

**Comment by bzw1204** [comment]
> 版本：1.9.2 当前最新release 系统：win10
> 
> 使用UI上的+号多次新建会话会导致卡住无法新建
> 
> 每次新建的会话都是真实有效的，多建几次就会发现，再点加号，左侧会话栏没有出现新的未命名主机，但是新建会话的界面显示了，然后填好设置以后，是无法保存，无法连接的
> 
> Feature： 导出的时候能不能选择性导出，而不是默认所有会话都导出了
> 
> 还有一点，所有UI交互都有一点卡卡的感觉，对比xshell等其他shell，绝对没有这种迟滞的感觉

最新版本中已修复这个问题，请更新使用
