### ISSUE TITLE
update notification on latest version

### ISSUE THREAD

**Issue by sino1641** [nxshell/nxshell#257]
**Describe the bug**
app showing update notification even it is my first time download it.
**To Reproduce**
1. Download latest 1.9.0 and open it.
2. see error

**Expected behavior**
IDK, maybe no update notification?
**Screenshots**
![image](https://user-images.githubusercontent.com/13870295/213152978-631049f6-f10f-4942-8ba3-e92c82823edf.png)

**Desktop (please complete the following information):**
 - OS win11
 - OS Version 22h2
 - NxShell Version 1.9.0

**Additional context**
-

**Comment by bzw1204** [comment]
please download file in here http://106.15.238.81:52081/github/
