### ISSUE TITLE
关于USB转串口调试由于 nxshell不能获取root权限而失败

### ISSUE THREAD

**Issue by qhfzh** [nxshell/nxshell#260]
usb转串口调试提示要root权限，加pkexec或sudo运行报错，发现nxshell根本不支持在root权限下运行。然和ttyUSBx这类设备需要root权限才能调试，由于经常使用usb转串口调试我不得不改用Windterm。

**Comment by bzw1204** [comment]
> usb转串口调试提示要root权限，加pkexec或sudo运行报错，发现nxshell根本不支持在root权限下运行。然和ttyUSBx这类设备需要root权限才能调试，由于经常使用usb转串口调试我不得不改用Windterm。

请问有操作视频或者截图吗？请提供一下

**Comment by qhfzh** [comment]
图片中展示的是普通用户点击运行，没有管理员权限无法调试串口，Windterm也一样。Windterm加sudo就行了，nxshell则不行，看下面两段加入sudo报错。
![普通用户运行效果](https://user-images.githubusercontent.com/50522711/221340676-3939040d-fe24-4e2b-b872-ea73dd7a6f6b.png)

[0225/133056.918110:FATAL:electron_main_delegate.cc(291)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
fish: “sudo ./NxShell-x86_64-linux-1.9…” terminated by signal SIGTRAP (Trace or breakpoint trap)

[0225/133811.864140:FATAL:electron_main_delegate.cc(291)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
fish: “sudo nxshell” terminated by signal SIGTRAP (Trace or breakpoint trap)

**Comment by nxshell** [comment]
sudo nxshell --no-sandbox  @qhfzh
