### ISSUE TITLE
很奇怪，我用nxshell时。 git clone，github上的代码，就要输入账号密码。还提示失败。

### ISSUE THREAD

**Issue by fyyxxm** [nxshell/nxshell#264]
用xshell和 vscode的 ssh就可以。也不用输入密码。。。。

**Comment by bzw1204** [comment]
> 用xshell和 vscode的 ssh就可以。也不用输入密码。。。。

请问下你是链接的ssh git clone 还是 localshell

**Comment by fyyxxm** [comment]
是https 的链接 clone

**Comment by nxshell** [comment]
try use git protocol,not https



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年03月29日 08:33 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | Re: [nxshell/nxshell] 很奇怪，我用nxshell时。 git clone，github上的代码，就要输入账号密码。还提示失败。 (Issue #264) |

是https 的链接 clone
