### ISSUE TITLE
设置后无法按照设置显示

### ISSUE THREAD

**Issue by zhaohuaxi-Shi** [nxshell/nxshell#281]
修改主题或者字体什么的能保存, 但是界面无法按照设置的展示

**Comment by bzw1204** [comment]
> 修改主题或者字体什么的能保存, 但是界面无法按照设置的展示

修改的主题或字体无法应用到已经打开的终端当中，新打开一个看看

**Comment by zhaohuaxi-Shi** [comment]
> > 修改主题或者字体什么的能保存, 但是界面无法按照设置的展示
> 
> 修改的主题或字体无法应用到已经打开的终端当中，新打开一个看看

我动重启了也没用

**Comment by bzw1204** [comment]
> > > 修改主题或者字体什么的能保存, 但是界面无法按照设置的展示
> > 
> > 
> > 修改的主题或字体无法应用到已经打开的终端当中，新打开一个看看
> 
> 我动重启了也没用

到群里发截图看看
