### ISSUE TITLE
希望加入更多的串口波特率支持，或者串口自定义

### ISSUE THREAD

**Issue by heimareed** [nxshell/nxshell#284]
如题，我经常调试嵌入式平台。一方面是SSH进Linux系统操作，同时会利用UART操作，目前支持的波特率偏低，希望能加入更多的波特率，或者能够自定义波特率（手写输入即可）。

**Comment by bzw1204** [comment]
> 如题，我经常调试嵌入式平台。一方面是SSH进Linux系统操作，同时会利用UART操作，目前支持的波特率偏低，希望能加入更多的波特率，或者能够自定义波特率（手写输入即可）。

最新版本已经支持自定义，到官网去下载使用

**Comment by heimareed** [comment]
> > 如题，我经常调试嵌入式平台。一方面是SSH进Linux系统操作，同时会利用UART操作，目前支持的波特率偏低，希望能加入更多的波特率，或者能够自定义波特率（手写输入即可）。
> 
> 最新版本已经支持自定义，到官网去下载使用

1.9.5版本，点击新建Serial对话，弹窗缺是SSH，压根出不来Serial窗口

**Comment by Maihuanyi** [comment]
新版的还是没有自定义串口波特率

**Comment by yoozaa80** [comment]
串口波特率  还是 需要 有 自定义 选项 ， 这个值在调试中 会有无穷值的可能

**Comment by blueveryday** [comment]
最新版自定义波特率不可用，期待解决，谢谢。

**Comment by bzw1204** [comment]
> 最新版自定义波特率不可用，期待解决，谢谢。

最新版本V1.9.6已修复串口新建的bug，请到官网下载使用 
![image](https://github.com/nxshell/nxshell/assets/9693637/17454708-38a2-4c81-adf1-e1496457d4a5)
自定义串口可以在点击波特率那里自行填写
