### ISSUE TITLE
language keeps defaulting to Chinese

### ISSUE THREAD

**Issue by westhecool** [nxshell/nxshell#287]
**Describe the bug**
language keeps defaulting to Chinese.
Changes back to English when I open the setting menu.

**Desktop:**
 - OS: Window11
 - NxShell Version v1.9.3

**Comment by westhecool** [comment]
> > open the setting menu.
> 
> Please update to 1.9.5 for use. http://106.15.238.81:52081/github/

The installer is not opening. Also why not publish to github?

**Comment by bzw1204** [comment]
> > > open the setting menu.
> > 
> > 
> > Please update to 1.9.5 for use. http://106.15.238.81:52081/github/
> 
> The installer is not opening. Also why not publish to github?

No push for the time being, the boss is very busy recently
