### ISSUE TITLE
建议借鉴electerm，提供打开 sftp时指定目录的功能

### ISSUE THREAD

**Issue by chang7v** [nxshell/nxshell#29]
有时目录层级较多，希望打开时就在指定目录下，希望可以提供这个功能，谢谢 ![image](https://user-images.githubusercontent.com/31920080/125879395-43c6bfe7-3897-47bc-b708-fa3db74247e9.png)

**Comment by nxshell** [comment]
Release v1.4.0， 在配置session里面配置
