### ISSUE TITLE
1.9.5版本中串口模式无法进入

### ISSUE THREAD

**Issue by zelsazgh** [nxshell/nxshell#290]
新版本1.9.5当中，Serial模式无法进入，点击后切换成新建SSH会话窗口，而不是Serial会话新建窗口

**Comment by bzw1204** [comment]
> 新版本1.9.5当中，Serial模式无法进入，点击后切换成新建SSH会话窗口，而不是Serial会话新建窗口

已更新修复，请到官网下载最新的1.9.6使用
