### ISSUE TITLE
Nxshell近期有支持MFA的计划吗？

### ISSUE THREAD

**Issue by Changego** [nxshell/nxshell#30]
各位好，Nxshell 是个不错的工具，眼前一亮。UI也很和谐。
但是目前兼容性待提高。
很多公司都需堡垒机登陆机器的。而堡垒机一般都会开放MFA等双因子认证的。
毕竟能直连的场景其实蛮少。所以想问下，近期有无支持MFA的计划啊？

**Comment by nxshell** [comment]
@Changego 感谢反馈，这个能加QQ群199234440具体沟通下吗？

**Comment by nxshell** [comment]
fix 1.4.2
