### ISSUE TITLE
为什么选中会自动触发ctrl+c

### ISSUE THREAD

**Issue by ENE033** [nxshell/nxshell#332]
如题
![image](https://github.com/user-attachments/assets/ba2d8050-575a-4914-b233-d53ba93e82cb)

![image](https://github.com/user-attachments/assets/8a7a6f6b-ce91-4a6d-974c-ef774e189cea)

**Comment by yangzishy** [comment]
你解决了吗  朋友

**Comment by ENE033** [comment]
> 你解决了吗 朋友

钉钉的ai助手的问题

**Comment by zhanghaodongz** [comment]
鼠标同时按住左键+右键就好了
