### ISSUE TITLE
字体设置是写死的3个选项吗

### ISSUE THREAD

**Issue by bzw1204** [nxshell/nxshell#39]
1. 请问下字体的设置是写死的三个字体吗，不能选择系统安装的其他字体吗

**Comment by etanman** [comment]
三种字体的确效果都不太好

**Comment by nxshell** [comment]
获取系统字体列表展示，正在开发中

**Comment by etanman** [comment]
太好了，现有只有默认字体比较舒服一点，可惜是小写l与数字1不容易分辨，这个运维过程中很容易造成麻烦。

**Comment by nxshell** [comment]
release v1.4.3
