### ISSUE TITLE
终端能不能增加目录和文件的颜色区分？

### ISSUE THREAD

**Issue by etanman** [nxshell/nxshell#45]
现在更出目录时没有任何颜色区分，不是太方便。

**Comment by nxshell** [comment]
![图片](https://user-images.githubusercontent.com/74552956/128797068-500c57aa-8a0b-4af5-bffa-2c17dd56d4d5.png)
默认是有的，是不是你的linux shell 终端要配置下

**Comment by etanman** [comment]
是我这哪设置不对吗？
![Uploading Snipaste_2021-08-16_08-44-32.png…]()

**Comment by nxshell** [comment]
Linux服务器的设置，可以百度谷歌一下ls不显示颜色的问题。

**Comment by etanman** [comment]
> Linux服务器的设置，可以百度谷歌一下ls不显示颜色的问题。

感谢您的回复，再问下字体不可以自定义吗？
