### ISSUE TITLE
希望sftp更加完善一些

### ISSUE THREAD

**Issue by etanman** [nxshell/nxshell#46]
现在连基本的键盘按文件或文件夹首字母查找功能也没有，另外可以参考一下MobaXterm这个软件的sftp右键菜单，增加open with功能，用第三方软件可以打开并且保存回服务器，这个在运维时最常用到的功能。
看了日志，nxshell竟然是今年现发行的1.0版本，做到这个程度非常了不起了，终端软件现在非常确少一个像这样的跨平台软件，三个平台都可以用，还是开源软件，前景非常看好呀，三年后能不能一统江湖？将来能不能超载MobaXterm？

**Comment by nxshell** [comment]
@etanman  sftp 查找文件功能在右上角可以查找文件啊，输入。  集成三方编辑器正在开发中。 最后感谢关注nxshell。

**Comment by etanman** [comment]
不好意思，没表达清楚，不是查找功能，是通过键盘按首字母快速定位到文件夹或者文件。

**Comment by gridnow** [comment]
> 不好意思，没表达清楚，不是查找功能，是通过键盘按首字母快速定位到文件夹或者文件。
> 另外，集成第三方编辑无所谓，能用第三方打开就好，比如vscode.

我们研究下。

**Comment by nxshell** [comment]
same as #206
