### ISSUE TITLE
界面优化

### ISSUE THREAD

**Issue by weipengcheng1** [nxshell/nxshell#54]
![image](https://user-images.githubusercontent.com/49983314/129999687-9bb14c8e-9a03-4c54-89d5-76f08a478c12.png)
希望可以将页面进行优化一下， 
![image](https://user-images.githubusercontent.com/49983314/129999729-852622cb-9a65-4f7a-b7dd-11be4e66e40b.png)
左边懒图标太大了，颜色搭配也有点儿不协调
同时希望增加在线编辑功能

**Comment by etanman** [comment]
左边图标的确有些大了，颜色问题是个人喜好问题，希望加入皮肤功能，由用户决定。
在线编辑功能的确太需要了，后面尽快再加入telnet，基本就可以达到代替其他终端的水准了。
需要注意的是telnet中的字段颜色也十分重要，希望开发的时候考虑一下。
![20210822184725](https://user-images.githubusercontent.com/45775943/130352445-85b27734-fb68-470d-bae8-2d51e152509f.png)
