### ISSUE TITLE
sftp文件太多依旧会卡死

### ISSUE THREAD

**Issue by bzw1204** [nxshell/nxshell#57]
![image](https://user-images.githubusercontent.com/9693637/130374340-9b16febb-80ee-4f3d-aa45-1cad06e63429.png)
1. 我测试的目录中大概有8700多照片文件，现在打开会卡一会展示出来，但是无法正常操作，任何操作都要卡主很久
2. 当我视图移动名称栏目时出现标题栏与内容错位
建议：

是否可以默认加载一屏的内容，后台异步加载后续内容，不要影响操作使用

**Comment by nxshell** [comment]
渲染分屏问题修复了，一次sftp读取目录还是有点慢。读取完后，加载分屏有所优化。

**Comment by bzw1204** [comment]
辛苦了……

**Comment by waittingsummer** [comment]
我发现sftp目录下文件稍微多一点，不管怎么上拉 下拉都找不到文件，但是在搜索框打个关键字，马上就能看到了

**Comment by nxshell** [comment]
@waittingsummer  能截图看看吗？找不到

**Comment by waittingsummer** [comment]
> @waittingsummer 能截图看看吗？找不到
![1](https://user-images.githubusercontent.com/32017265/134880137-01c307df-e261-48cf-8295-06400368067d.png)
![2](https://user-images.githubusercontent.com/32017265/134880148-7cd35001-edc8-47a1-a8f6-0d1f29bb3f2a.png)
![3](https://user-images.githubusercontent.com/32017265/134880149-f1ccade8-473b-45a3-80e6-9b70712b77af.png)
图三的压缩包是我要找的   图1 图2  拉到底或者拉到顶或者在这个过程中都没找到这个文件

**Comment by nxshell** [comment]
release 1.4.5
