### ISSUE TITLE
table标签加优化

### ISSUE THREAD

**Issue by mahaiwuji** [nxshell/nxshell#59]
关闭最好细化一点
![QQ图片20210823193422](https://user-images.githubusercontent.com/60996116/130440590-4d7db540-6736-4d64-b35e-a94bc6a79ae4.png)
最好窗口多了再加个切换的按钮
![QQ图片20210823193500](https://user-images.githubusercontent.com/60996116/130440655-f6f1ab85-4567-4688-90bf-148f34797289.png)

**Comment by nxshell** [comment]
release v1.4.3
