### ISSUE TITLE
标签页问题

### ISSUE THREAD

**Issue by DemonCode2012** [nxshell/nxshell#69]
有2个小问题。  
1. 我改了 会话的名字 左边好像没有更新
<img width="664" alt="hostname" src="https://user-images.githubusercontent.com/48744524/132480786-2bc8e714-c003-4377-98b3-1c1239e6e37f.png">

2. 右键duplicate session 就找不到原来的标签页了
<img width="502" alt="tab" src="https://user-images.githubusercontent.com/48744524/132480795-1aab79c1-7633-4426-8872-23e23b2296fe.png">

**Comment by nxshell** [comment]
操作系统？ 怎么复现的？我这边咱没有能复现问题2

**Comment by DemonCode2012** [comment]
> 操作系统？ 怎么复现的？我这边咱没有能复现问题2

win10 
我就是右键 123 然后create session 结果直接覆盖了原来的连接。

**Comment by bzw1204** [comment]
请更新到最新版本体验！
