### ISSUE TITLE
显示方式按照详细信息显示，右边滚动栏滚动有bug

### ISSUE THREAD

**Issue by mmst0727** [nxshell/nxshell#70]
1、显示方式选择详细信息的时候，右边滚动栏滚动进度跟文件列表显示不同步，在滚动栏到底的时候，实际上只是在上面的文件夹滚动完了，鼠标再往下滚动才能显示文件；向上滚动滚动栏到顶部只是下面的文件滚动完毕，文件夹目录还要继续滚鼠标轮才能显示。
2、在显示详细信息的时候，双击进入一些文件夹会误点开其他的文件夹，比如/etc/selinux文件夹就进不去。
3、能不能默认按照文件名排序并且文件夹在上面，现在的文件排序方式找文件太费劲了。
4、显示方式为详细信息的时候，有一些文件夹不显示。

**Comment by nxshell** [comment]
能加群详细截图看看嘛，我这边没能复现。。。

**Comment by nxshell** [comment]
![图片](https://user-images.githubusercontent.com/74552956/132528355-87807df1-6e9e-4ba0-816d-a8a7926baf93.png)
默认也是按照文件夹排序的。。。

**Comment by nxshell** [comment]
问题2，已复现
