### ISSUE TITLE
BUG: 设置按钮进入设置，字体无法选择系统字体，仅可以选择内置的3个选项

### ISSUE THREAD

**Issue by bzw1204** [nxshell/nxshell#72]
1. 设置按钮进入全局设置，字体无法选择系统字体，仅可以选择内置的3个选项
2. 
![image](https://user-images.githubusercontent.com/9693637/132780813-471d2c05-d266-4c01-8294-ba8d78107bba.png)

**Comment by nxshell** [comment]
Relase v1.4.4
