### ISSUE TITLE
BUG： 链接重复，导致命令重复输入

### ISSUE THREAD

**Issue by bzw1204** [nxshell/nxshell#73]
1. 当网络出现故障或卡顿时，如果一直点击刷新按钮或回车，当链接畅通时，会导致命令输入重复
![8b48ee88e7c51496c7b470865f5ba9d](https://user-images.githubusercontent.com/9693637/132780998-a2b74f41-7fff-4e19-9c2c-028168552902.png)

可复现操作步骤：
1. 断开网络连接
2. 打开一个服务器链接
3.  一直点击刷新按钮，或者回车操作待出现N多网络异常提示时，恢复网络
4. 输入命令观察现象（如上图所示）

**Comment by nxshell** [comment]
Relase v1.4.4
