### ISSUE TITLE
优化建议综合

### ISSUE THREAD

**Issue by bzw1204** [nxshell/nxshell#74]
1. 添加最新版本，或者可以检测更新，并显示新版本更新内容
2. 是否可以将SFTP界面并合到ssh界面，不用单独打开一个页签（如果支持设置更好）
3. sftp界面显示方式建议更换为图标操作放于操作栏会更方便
4. sftp显示为详细信息时，可以排序的列建议添加一个图标标识（另目前只支持排序一次，无法切回排序之前）
5. 可否新增服务器监控信息
6. 布局，如果有UI大神改，就不管了，如果没有，能不能将化框的三个合并为一个，然后把空出来的位置合并到内容区（如下图示）
![a0bcb25ec1ba0dc76a54dc885cdb3d9](https://user-images.githubusercontent.com/9693637/132781886-7d40fd59-1db6-456f-a8cd-a11d8316b2ee.png)

**Comment by etanman** [comment]
SFTP和ssh不能在同一标签显示的确有时候不方便

**Comment by etanman** [comment]
相信到了2.0版本一切都会好的，现在就缺一个这样的全平台的终端软件，都说Termius好，用了才知道哪玩艺真的不好用，希望nxshell尽快支持telnet，也希望支持安卓，鸿蒙。

**Comment by hummingsoul** [comment]
想加服务器监控 你干嘛不去用FinalShell   就烦它那个服务器监控信息显示 没卵用还耗资源
