### ISSUE TITLE
发现在vim编辑时不支持鼠标选择

### ISSUE THREAD

**Issue by etanman** [nxshell/nxshell#77]
无法选择文字，所以也无法复制。

**Comment by nxshell** [comment]
![图片](https://user-images.githubusercontent.com/74552956/133266424-153a8dc4-9b4a-4815-ae51-24b4b88d160d.png)
我这边可以啊？ 是不是vim要配置下？

**Comment by etanman** [comment]
的确是debian系统的原因，安装vim默认无法选择，修改vim配置解决了，谢谢。
