### ISSUE TITLE
终端字体显示需要进一步优化

### ISSUE THREAD

**Issue by etanman** [nxshell/nxshell#78]
![20210915090705](https://user-images.githubusercontent.com/45775943/133354137-fd020c8b-5cf6-48eb-968c-af559b9e6223.png)
同样采用了普遍好评的字体DejaVuSansMono，连接到了同一服务器。
左边是其他终端显示效果，右边是nxshell显示效果
nxshell的字间距稍微小了一些，能调整在大一点就好了，或者增加字间距调整功能。
另外nxshell对目录自动进行了加粗，所以显得更加拥挤和不清晰，希望不要对目录加粗。

**Comment by nxshell** [comment]
是字体太大了吧

**Comment by etanman** [comment]
默认12号字在高分辨率显示器下的确小了些，平时需要放大至14或16号，nxshell放大到16号字才达到了别的软件12号字的大小，上面截图上看以看到，左边软件是12号字，右边nxshell是16号，左边软件就没有任何问题，的确是nxshell字间距偏小了些，希望能够调整一些，谢谢。
