### ISSUE TITLE
点击左侧会话页签会跟着变动,但是点击页签左侧会话就不会变了

### ISSUE THREAD

**Issue by toy3536** [nxshell/nxshell#81]
![image](https://user-images.githubusercontent.com/90740710/133363963-34d2420a-b06d-4119-8a3e-483d202e4389.png)

**Comment by bzw1204** [comment]
右侧菜单栏的操作逻辑与Tab签不一样，菜单栏有更多的操作逻辑，避免异常操作故不支持双向同步！感谢您的支持与建议！请更新到最新版体验！
