### ISSUE TITLE
几点建议

### ISSUE THREAD

**Issue by qwer130140190** [nxshell/nxshell#90]
1 sftp的tab标题能不能显示服务器名称
2 希望能够增加服务器导入导出功能，方便多台机器上使用
3 希望有一个更好的上传下载任务列表
4 希望能优化一下ui，不太美观，electron的话，可以使用很多炫酷的ui框架
5 希望增加左侧服务器列表折叠功能
6 tab的宽度希望能够自适应，有些服务器标题就3个字，也要占用这么长，tab多了就不直观了

**Comment by waittingsummer** [comment]
问题2   已经有，在列表空白出右键单击看下

**Comment by nxshell** [comment]
1、6 fix在v1.4.5

**Comment by li1220** [comment]
建议

**Comment by li1220** [comment]
建议 1.新增加服务器时默认交互输入  2.交互输入账号密码时可以增加保存账号和密码选项 3.交互输入时可以回车确认
