### ISSUE TITLE
v1.4.5 ssh登录时输入用户名后：Error: All configured authentication methods failed

### ISSUE THREAD

**Issue by li1220** [nxshell/nxshell#91]
![image](https://user-images.githubusercontent.com/45218382/135377325-ac5ce8d0-d53f-460e-aa94-767436dd009c.png)

**Comment by nxshell** [comment]
@li1220 登录方式选择interactive 试一下。或者在配置password方式里面把用户名密码都输入到配置文件里面。

**Comment by li1220** [comment]
感觉 @nxshell  可以了
